version: '3.8'

services:
  server:
    image: ${DOCKER_HUB_USERNAME}/gym-server:latest
    ports:
      - "5000:5000"
    env_file:
      - .env # Ensure you create an .env file on your EC2 instance containing your backend environment variables
    restart: always

  client:
    image: ${DOCKER_HUB_USERNAME}/gym-client:latest
    ports:
      - "80:5173" # Mapping port 80 (HTTP) to the client app container
    env_file:
      - .env # Ensure you create an .env file on your EC2 instance containing your frontend environment variables
    depends_on:
      - server
    restart: always
