version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build: ./client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
